# Site settings
title: pblog
description: 技術解説とプログラミング学習のブログ
baseurl: ""
url: "https://somadevfat.github.io/pblog"

# Author
author: 
  name: soma
  email: your-email@example.com

# Build settings
markdown: kramdown
highlighter: rouge
# theme: minima  # テーマを無効化してREADME表示問題を解決

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

# Collections for future use
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Pagination (for future)
paginate: 5
paginate_path: "/page:num/" 